version: "2.1"
services:
  service-a:
    image: "harbor.aigauss.com/test/service-a:v2"
    build: ./service-a
    ports:
      - 18080:8080
    environment:
      - SERVICE_FORMATTER=service-b
  service-b:
    image: "harbor.aigauss.com/test/service-b:v2"
    build: ./service-b
    ports:
      - 18081:8080
    environment:
      - SERVICE_FORMATTER=service-c
  service-c:
    image: "harbor.aigauss.com/test/service-c:v2"
    build: ./service-c
    ports:
      - 18082:8080
